# Generated by Django 2.0.1 on 2018-01-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField()),
                ('title_text', models.CharField(max_length=200)),
                ('content_text', models.TextField()),
            ],
        ),
    ]
