# Generated by Django 2.0.1 on 2018-01-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadableFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField()),
                ('title_text', models.CharField(max_length=300)),
                ('info_text', models.TextField()),
                ('file_to_download', models.FileField(upload_to='')),
            ],
        ),
    ]
