# Generated by Django 2.0.1 on 2018-01-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadablefile',
            name='file_to_download',
            field=models.FileField(upload_to='files/media/'),
        ),
    ]
