# Generated by Django 2.0.1 on 2018-01-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0002_auto_20180121_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadablefile',
            name='info_text',
            field=models.TextField(default=' '),
        ),
    ]
